[package]
name = "page_table"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Generic page table structures for various hardware architectures"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/crates/page_table"
documentation = "https://rcore-os.github.io/arceos/page_table/index.html"

[dependencies]
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
cfg-if = "1.0"
memory_addr = { git = "ssh://git@github.com/shilei-massclouds/memory_addr" }
page_table_entry = { git = "ssh://git@github.com/shilei-massclouds/page_table" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal" }
axalloc = { git = "ssh://git@github.com/shilei-massclouds/axalloc" }