[package]
name = "axstd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[features]
default = []
print = []

[dependencies]
axlog2 = {  path = "../axlog2/axlog2" } 