[package]
name = "fileops"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
task = { git = "ssh://git@github.com/shilei-massclouds/task.git" }
axfile = { git = "ssh://git@github.com/shilei-massclouds/axfile.git" }
mutex = { git = "ssh://git@github.com/shilei-massclouds/mutex.git" }
axerrno = { git = "ssh://git@github.com/shilei-massclouds/axerrno.git" }
axio = { git = "ssh://git@github.com/shilei-massclouds/axio.git" }
axtype = { git = "ssh://git@github.com/shilei-massclouds/axtype.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal.git" }
early_console = { git = "ssh://git@github.com/shilei-massclouds/early_console.git" }
axdriver = { git = "ssh://git@github.com/shilei-massclouds/axdriver" }
axmount = { git = "ssh://git@github.com/shilei-massclouds/axmount" }
axconfig = { git = "ssh://git@github.com/shilei-massclouds/axconfig" }
axalloc = { git = "ssh://git@github.com/shilei-massclouds/axalloc" }
page_table = { git = "ssh://git@github.com/shilei-massclouds/page_table" }
axlog2 = { git = "ssh://git@github.com/shilei-massclouds/axlog2" }
axfs_vfs = { git = "ssh://git@github.com/shilei-massclouds/axfs_vfs" }
capability = { git = "ssh://git@github.com/shilei-massclouds/capability" }
mm = { git = "ssh://git@github.com/shilei-massclouds/mm" }
axfs_pipefs = { path = "../../axfs_pipefs/axfs_pipefs" }
signal = { git = "ssh://git@github.com/shilei-massclouds/signal" }

[target.'cfg(any(target_arch = "riscv32", target_arch = "riscv64"))'.dependencies]
riscv = "0.10"
