[package]
name = "axfs_devfs"
version = "0.1.0"
edition = "2021"
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Device filesystem used by ArceOS"
license = "GPL-3.0-or-later OR Apache-2.0"
homepage = "https://github.com/rcore-os/arceos"
repository = "https://github.com/rcore-os/arceos/tree/main/crates/axfs_devfs"
documentation = "https://rcore-os.github.io/arceos/axfs_devfs/index.html"

[dependencies]
spin = "0.9"
log = "0.4"
axfs_vfs = { git = "ssh://git@github.com/shilei-massclouds/axfs_vfs.git" }
axhal = { git = "ssh://git@github.com/shilei-massclouds/axhal.git" }
run_queue = { git = "ssh://git@github.com/shilei-massclouds/run_queue.git" }
